/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface YButton {
        "size": 'sm' | 'md' | 'lg' | 'xl';
        "variant": 'primary' | 'destructive' | 'outline' | 'secondary' | 'link';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLYButtonElement extends Components.YButton, HTMLStencilElement {
    }
    var HTMLYButtonElement: {
        prototype: HTMLYButtonElement;
        new (): HTMLYButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "y-button": HTMLYButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface YButton {
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
        "variant"?: 'primary' | 'destructive' | 'outline' | 'secondary' | 'link';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "y-button": YButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "y-button": LocalJSX.YButton & JSXBase.HTMLAttributes<HTMLYButtonElement>;
        }
    }
}
